Data analysis and story telling


# numpy
date: 24/11/2023
Creating array using numpy - three methods
using empty
      zeros or ones
      array

In [1]:
import numpy as np
a= np.empty((2,3,2),dtype=int)   # creating array using numpy
print(a)

[[[1374602864        478]
  [1352848752        478]
  [1357838064        478]]

 [[1357838000        478]
  [1357838128        478]
  [1419026416        478]]]


In [2]:
b=np.zeros((3,6))    # ones for one in zero place here
b
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
b=np.zeros((3,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
b=np.ones((3,6))    # ones for one in zero place here
b
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [5]:

data= [[2,3,4,5],[7,9,5,6]]
c=np.array(data)
c

array([[2, 3, 4, 5],
       [7, 9, 5, 6]])

In [6]:
print(c)

[[2 3 4 5]
 [7 9 5 6]]


In [7]:
import numpy as np
X = np.full((2,3), 5)
X

array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
import numpy
arr1=numpy.array([1,2,3,4])
arr1.shape

(4,)

In [10]:
#logical operator 
arr2=arr1>2
arr2

array([False, False,  True,  True])

In [11]:
#grouping operator 
import numpy
b=[1,2,3],[4,5,6]
val=numpy.array(b)
val1=val*val
val1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
arr1.dtype

dtype('int32')

# Universal function
     1]unary ufunc
     2]binary ufunc

In [7]:
#1}unary ufunc



import numpy as np

x=np.random.randn(7)
print("x:",x)

y=[1,2,3,4]
a=np.abs(y)
print("abs:",a)

b=np.fabs(y)
c=np.sqrt(y)
print("fabs:",b)
print("sqrt:",c)


q = np.ceil(y)

print("ceil:",q)

e=np.log(y)    # or np.log(1)
print("log:",e)
k=np.isinf(y)
print("inf:",k)
f=np.log1p(y)
print("log1p",f)
h=np.cos(y)
g=np.arcsin(y)
i=np.logical_not([9])
print("cos:",h,"arcsin:",g,"logical_not:",i)


x: [ 0.23660038  1.57845442  1.04110171  1.52595416 -1.0964217   0.63672949
 -0.00495455]
abs: [1 2 3 4]
fabs: [1. 2. 3. 4.]
sqrt: [1.         1.41421356 1.73205081 2.        ]
ceil: [1. 2. 3. 4.]
log: [0.         0.69314718 1.09861229 1.38629436]
inf: [False False False False]
log1p [0.69314718 1.09861229 1.38629436 1.60943791]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362] arcsin: [1.57079633        nan        nan        nan] logical_not: [False]


C:\Users\SARAVANAN\AppData\Local\Temp\ipykernel_23140\2649400259.py:31: RuntimeWarning: invalid value encountered in arcsin
  g=np.arcsin(y)


In [16]:
#binary universalfuction
import numpy as np

x=[[-2,3],
   [2,3]]      # array size is important  just like matrix
y=np.eye(2)
print("array:")
print(x)
print(y)

a=np.add(x,y)
print("add",a)
b=np.maximum(x,y)
print("max:",b)


c=np.copysign(x,y)   #  takes second argument sign to first argument sign 
print("copysign:",c)


d=np.logical_and(x,y)
print("logical_and:",d)

e=np.logical_and(a,b)      # see difference
print("logical_and:",e)
 
    
    # for use two dimensional use two square bracket otherwise  it will shows error
    
arr=np.array([[1,2],[8,4]])           
pro_array=np.prod(arr,axis=0)
pro_array1=np.prod(arr,axis=1)   # axis=0          [[a,b],[c,d]] = [ac  bd]    it doing process in horizondal format,
                               #axis=1 for vertical format[ab  cd]
print(pro_array)
print(pro_array1)


# arange
arr1=np.arange(10)
arr2=np.arange(5,10)
arr3=np.arange(10,1,-1)
print(arr1)                                   # (starts,ends,no.of element)
print(arr2)
print(arr3)




array:
[[-2, 3], [2, 3]]
[[1. 0.]
 [0. 1.]]
add [[-1.  3.]
 [ 2.  4.]]
max: [[1. 3.]
 [2. 3.]]
copysign: [[2. 3.]
 [2. 3.]]
logical_and: [[ True False]
 [False  True]]
logical_and: [[ True  True]
 [ True  True]]
[8 8]
[ 2 32]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[10  9  8  7  6  5  4  3  2]


# File input and output with array

Using numpy
-------------------
**File Input  : 

           It allows you to read data from text files using function like 
           
           numpy.loadtxt()
           
    or    numpy.genfromtxt()
    
**File Output: 
               
           you can save Numpy arrays to a file using fuctions like 
           
           numpy.savetxt()
           
using pandas
-------------------
**File Input:
            
            pandas provides function like
           
           
               pandas.read_csv 
           
            or pandas.read_excel()       to read data from CSV or EXcel files.
            
            
**File Output:

           you can write dataframes to files using methods like 
           
              to_csv()  
           or to_excel()


In numpy
-------------

In [10]:
y=[1,2,3,4]
q=np.ceil(y)
np.save("my_file",q)
np.load("my_file.npy")

array([1., 2., 3., 4.])

In [11]:
y=[1,2,3,4]
q=np.ceil(y)
np.savez("my_file",q)     #savez("my_file",q)
np.load("my_file.npy")

array([1., 2., 3., 4.])

In [13]:
y=[1,2,3,4]
q=np.ceil(y)
np.savetxt("my_file_me.txt",q)
np.loadtxt("my_file_me.txt")

array([1., 2., 3., 4.])

in "my_file_me.txt"


1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00


  In pandas 
  ---------------
           WE can get directly from csv
            or
           write data in csv file  like creating csv file
        

In [8]:
import pandas as pd
data=pd.read_csv('employee_data.csv')
print(data)

     number first_name last_name gender  birth_date employment_status  \
0       483     Lenord      Kihn      M  1994-07-01               NaN   
1       478      Palma    Beahan      F  1972-05-06                PE   
2       348     Hebert    Muller      M  1990-09-04                PE   
3       757   Virginia   Ullrich      M  1991-09-23                PE   
4       937       Roby    Hudson      M  1997-01-15               NaN   
..      ...        ...       ...    ...         ...               ...   
995     712       Dann    Crooks    NaN  1983-12-25                CA   
996     132      Maxim       Orn      M  1971-03-01                CA   
997     126   Kimberli    Walter      M  1976-03-07                CA   
998     277    Talmage   Bartell      F  1989-02-19                PE   
999     960     Laurie    Nienow      M  1993-04-01                PE   

     annual_salary  tax_file_no  
0          64598.0          NaN  
1         124103.0          NaN  
2         100324.0   

In [6]:
import pandas as pd

data=pd.DataFrame({'a':[1,2,3],'b':['g','c','g']})
datas=data.to_csv('output_file.csv',index=False)
print(datas)               
print(data)

None
   a  b
0  1  g
1  2  c
2  3  g


# pandas



In [23]:
import pandas as pd
my_data={'person':['niva','nivi','harsha'],'age':['19','20','21']}
val=pd.DataFrame(my_data) 
print("data:",val)                        # only capital use for DataFrame not use dataframe, Datafram   cause error



a=val.head()
print("head:",a)
b=val.tail()
print("tail:",b)
c=val.head()
print("head1:",c)
d=val.tail()
print("tail2:",d)






data:    person age
0    niva  19
1    nivi  20
2  harsha  21
head:    person age
0    niva  19
1    nivi  20
2  harsha  21
tail:    person age
0    niva  19
1    nivi  20
2  harsha  21
head1:    person age
0    niva  19
1    nivi  20
2  harsha  21
tail2:    person age
0    niva  19
1    nivi  20
2  harsha  21


In [27]:
why=[1,3,4,5]

myvalue=pd.Series(why)
myvalue

0    1
1    3
2    4
3    5
dtype: int64

In [31]:
my_value1=pd.Series(why,index=['a','b','c','d'])
print(my_value1)

a    1
b    3
c    4
d    5
dtype: int64


In [34]:
my_value1["c"]

4

# ii)DataFrame  

     DataFrame is a two dimensional labeled structure.Data  is aligned in a tabular format in rows and columns.
    It is faster and easy to use and more powerful than tables or spreadsheets.
    DataFrame is just similar to tablular look but table and dataframe are different data structure.
    We can say DataFrame is composed of multiple series.


In [4]:
data={'calories':[222,22,354],'duration':[2,5,6]}
df=pd.DataFrame(data)
df

calories  duration
0       222         2
1        22         5
2       354         6

In [1]:
import pandas as pd
data={'person':['aami','niva'],'age':[19,20]}
frame=pd.DataFrame(data)
frame

person  age
0   aami   19
1   niva   20

In [3]:
import numpy as np
my_frame=pd.DataFrame(np.arange(8).reshape(2,4),
                     index=['7 ','4']
                     ,columns=['a','c','e','1'])
my_frame


a  c  e  1
7   0  1  2  3
4   4  5  6  7

returning values by its location . 1st for this process , you have to make it as index   or use normal DataFrame(data,index=['one','two']

In [10]:
import pandas as pd
data={'person':['aami','niva'],'age':[19,20],'class':['a','a']}
frame=pd.DataFrame(data)

frame.set_index('person',inplace=True)
particular_row=frame.loc['aami']
particular_row

age      19
class     a
Name: aami, dtype: object

In [19]:
import pandas as pd
data={'person':['a','n'],'age':[19,20],'class':['a','b']}
frame=pd.DataFrame(data)  # compare this this both  are little bit same

frame=pd.DataFrame(data,index=['one','two'])
frame

person  age class
one      a   19     a
two      n   20     b

using numpy in pandas

In [16]:
import pandas as pd
import numpy as np
data={'person':['aami','niva'],'age':[19,20],'class':['a','a']}
frame=pd.DataFrame(data)
frame['class']=np.arange(2)
frame


person  age  class
0   aami   19      0
1   niva   20      1

In [23]:
frame['old']=frame.person=='aami'
frame                                          # answer is wrong

person  age class    old
one      a   19     a  False
two      n   20     b  False

In [5]:
data={'calories':[222,22,354],'duration':[2,5,6]}
df=pd.DataFrame(data)
df.loc[0]


calories    222
duration      2
Name: 0, dtype: int64

deleting particular column only 

In [24]:
del frame['old']                    
frame

person  age class
one      a   19     a
two      n   20     b

nested dict of dictionaries

In [28]:
import pandas as pd
data={'column1':{'row1':'a','row2':'b'},
         'column2':{'row1':'c','row2':'mb'}}
data

{'column1': {'row1': 'a', 'row2': 'b'}, 'column2': {'row1': 'c', 'row2': 'mb'}}

In [29]:
import pandas as pd
data={'column1':{'row1':'a','row2':'b'},
         'column2':{'row1':'c','row2':'mb'}}      
df=pd.DataFrame(data)
df

column1 column2
row1       a       c
row2       b      mb

clearly we can see difference in above code  (generally- to putting index or it automatically  consider index) .
here we create index column also in one code 

In [30]:
import pandas as pd
data={'name':{'person1':'a','person2':'b'},
         'age':{'person1':'19','person2':'20'}}      
df=pd.DataFrame(data)
df

name age
person1    a  19
person2    b  20

just Recall

In [4]:
import pandas as pd
data={'person':['niva','aami'],"age":["19",'18']}
data1=pd.DataFrame(data)
import numpy as np
data1['class']=np.arange(2)
data1

person age  class
0   niva  19      0
1   aami  18      1

                                                  Deleting the  column   and viewing the columns
                                                  
                                                  
                                                  
                                                  
                                                  
                                                  del framename['column_name_gonna_delete']
                                                  
                                                  framename.columns

In [5]:
del data1['class']
data1.columns

Index(['person', 'age'], dtype='object')

In [6]:
data1

person age
0   niva  19
1   aami  18

                                     
                                     
                                     
                                     See difference in nested dictionary

In [8]:
data={'person1':{'name': 'aami','year':'21'},'person2':{'name':'niva','year':'19'}}
dataframe=pd.DataFrame(data)
dataframe

person1 person2
name    aami    niva
year      21      19

In [9]:
data={'person1':{'name': 'aami','year':'21'},'person2':{'name':'niva','year':'19','age':'19'}}
dataframe=pd.DataFrame(data)
dataframe

person1 person2
name    aami    niva
year      21      19
age      NaN      19

In [4]:
data={'person1':{'name': 'aami','year':'21'},'person2':{'name':'niva','year':'19','age':'19'},'person3':{"name":'keerthi'}}
dataframe=pd.DataFrame(data)
dataframe

person1 person2  person3
name    aami    niva  keerthi
year      21      19      NaN
age      NaN      19      NaN

                             considering  index

In [5]:
pd.DataFrame(dataframe,index=['person1','person2','person3'])
dataframe

person1 person2  person3
name    aami    niva  keerthi
year      21      19      NaN
age      NaN      19      NaN

                       Transposition

In [6]:
transposed=dataframe.T
transposed

name year  age
person1     aami   21  NaN
person2     niva   19   19
person3  keerthi  NaN  NaN

In [18]:
pd.DataFrame(transposed,index=['person1','person2','person3'])
transposed

name year  age
person1     aami   21  NaN
person2     niva   19   19
person3  keerthi  NaN  NaN

                                     dataframe access  by slicing 
                                     
                                     
                                     
                                      for this method activate for only data must be indexed  
                                       here transposed 

In [21]:
# here "transposed is data frame , which is indexed also "
new_data={'student1':transposed['name'][:-1],}
new_data


{'student1': person1    aami
 person2    niva
 Name: name, dtype: object}

data={'person1':{'name': 'aami','year':'21'},'person2':{'name':'niva','year':'19','age':'19'},'person3':{"name":'keerthi'}}
frame1=pd.DataFrame(data)
new_data={'student1':frame1['name'][:-1]}     
new_data     
        # run this code it will shows error


                                 giving name for index row
                                 
                                 
                                 
                                 see difference for non indexed frame (frame1) and indexed frame (transposed)

In [12]:
import pandas as pd
data={'person1':{'name': 'aami','year':'21'},'person2':{'name':'niva','year':'19','age':'19'},'person3':{"name":'keerthi'}}
frame1=pd.DataFrame(data)
frame1.index.name='person'
frame1

person1 person2  person3
person                         
name      aami    niva  keerthi
year        21      19      NaN
age        NaN      19      NaN

In [11]:
transposed.index.name='person'
transposed

name year  age
person                    
person1     aami   21  NaN
person2     niva   19   19
person3  keerthi  NaN  NaN

                           Returns values of the data frame

In [13]:
transposed.values

array([['aami', '21', nan],
       ['niva', '19', '19'],
       ['keerthi', nan, nan]], dtype=object)

In [ ]:
Using CSV files 
WE can get files and access data .


df=pd.read_csv("file_name")
df.head()
                            

#  i)Series


one deminsion array  - similar type of numpy    
 it as fixed length , ordered dict(when mapping to index or considering real dictnary)
 
 
 
list to series
values returns
putting index
returning index
performing math operations
seriesmaking  in dictionary format
index making  and giving name to index column
Detect missing values  in pandas  which actually by isnull and notnull function in pandas 
one of the series feature  : data will automatically align by index

In [15]:
import pandas as pd
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [22]:
a.values


a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

                                 putting index  - see differences
    
    
    
    pd.Series(a,index=['a','b','c','d','e'])
    
    pd.Series(['1','2','3','4','5'],index=['a','b','c','d','e'])
    
                                

In [20]:
pd.Series(a,index=['a','b','c','d','e'])

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [21]:
pd.Series(['1','2','3','4','5'],index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: object

In [23]:
myseries=pd.Series(['1','2','3','4','5'],index=['a','b','c','d','e'])
myseries.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [2]:
import pandas as pd
calories={'day1':439,"day2":555,"day3":678}
myvar=pd.Series(calories,index=['day1','day2'])
myvar

day1    439
day2    555
dtype: int64

   performing operations     - using numpy functions or numpy_like operations such as boolean array, scalar multiplication, math function.
   
   
   *
   >,<
   exp

In [24]:
myseries*2      

a    11
b    22
c    33
d    44
e    55
dtype: object

In [30]:
a= pd.Series(['4','7','-5','a'])
a*2

0      44
1      77
2    -5-5
3      aa
dtype: object

In [29]:
a=pd.Series([4,7,-5])
a*2

0     8
1    14
2   -10
dtype: int64

above 
Here main difference is ,in series    the list values in quatation is consider as string values so it put two times
    soo don't put numerical value in quatation

In [33]:
#boolean 
myseries=pd.Series([1,2,3,5,4],index=['a','b','c','d','e'])                  # note: access by index 
'a'in myseries


True

In [36]:
# mistake making area
myseries=pd.Series([1,2,3,5,4],index=['a','b','c','d','e'])                  # note: access by index   it sees  the  index only
'1'in myseries                                                              # checking index based 


False

series making in dictionary format      

In [38]:
my_dict={'niva':"2l","aami":"1.5l"}
my_series=pd.Series(my_dict)
my_series

niva      2l
aami    1.5l
dtype: object

index making  and giving name to index column

In [42]:
name=['niva','aami']
a=pd.Series(my_series,index=name)
a.index

Index(['niva', 'aami'], dtype='object')

In [45]:
name

['niva', 'aami']

In [46]:
a

niva      2l
aami    1.5l
dtype: object

Detect missing values  in pandas  which actually by isnull and notnull function in pandas 



making non by extrarow data  in  index giving area

In [48]:
name=['niva','aami','anu']
a=pd.Series(my_series,index=name)
a

niva      2l
aami    1.5l
anu      NaN
dtype: object

In [49]:
pd.isnull(a)

niva    False
aami    False
anu      True
dtype: bool

In [50]:
pd.notnull(a)

niva     True
aami     True
anu     False
dtype: bool

 one of the series feature  : data will automatically align by index

In [51]:
a                # series one

niva      2l
aami    1.5l
anu      NaN
dtype: object

In [52]:
my_series            # 2nd series

niva      2l
aami    1.5l
dtype: object

In [53]:
a+my_series                        # automatically aligned for operation .
                                   #and it consider  zero for non datarow column (0+NaN)=NaN

aami    1.5l1.5l
anu          NaN
niva        2l2l
dtype: object

#   sorting 

sort_index  -> this is method for sorting 
 

In [6]:
import pandas as pd
import numpy as np
data=[1,2,3,5,6]
myseries=pd.Series(data)
myseries.sort_index()


0    1
1    2
2    3
3    5
4    6
dtype: int64

In [7]:
data=[1,2,3,4,5]
frame=pd.DataFrame(data)
frame.sort_index()

0
0  1
1  2
2  3
3  4
4  5

In [13]:
my_series=pd.Series(range(4),index=['b','v','a','d'])
my_series.sort_index()

a    2
b    0
d    3
v    1
dtype: int64

In [18]:
my_frame=pd.DataFrame(np.arange(8).reshape(2,4),
                     index=['7 ','4']
                     ,columns=['a','c','e','1'])
my_frame


a  c  e  1
7   0  1  2  3
4   4  5  6  7

In [19]:
my_frame.sort_index()

a  c  e  1
4   4  5  6  7
7   0  1  2  3

In [21]:
frame.sort_index(axis=1)


0
0  1
1  2
2  3
3  4
4  5

In [25]:
a=pd.Series([4,np.nan,7,np.nan,-3,2])
a.values
#a.sort_values()

array([ 4., nan,  7., nan, -3.,  2.])

In [26]:
series=[np.nan]
a=pd.Series()
a.values

C:\Users\SARAVANAN\AppData\Local\Temp\ipykernel_18008\745743667.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


array([], dtype=float64)

In [32]:
frame=pd.DataFrame({'b':[1,2,3,5],'a':[1,9,3,4]})
frame

b  a
0  1  1
1  2  9
2  3  3
3  5  4

sort by particular column  

 two method
     sort_values(by='a')
     sort_values('a')

In [33]:
frame.sort_values(by='a')

b  a
0  1  1
2  3  3
3  5  4
1  2  9

In [35]:
frame.sort_values('a')      # both are same

b  a
0  1  1
2  3  3
3  5  4
1  2  9


# Ranking 


seriesname.rank()
framename.rank()

                        dataframe_or_series_name.rank(method=' method name')


 method      describtion
    
average      default   average rank of each entry in the equal group
min          use the minimum rank for the whole group 
max          use the maximum rank for the whole group 
first        assign ranks in the order the values appear in the data
dense        l

=> min, max  with sorted in asecending and descending

=> ranking based on column and rows



In [3]:
import pandas as pd
name=pd.Series([7,3,5,6])
name.rank()

0    4.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [4]:
name.rank(method='first')

0    4.0
1    1.0
2    2.0
3    3.0
dtype: float64

    In ranking ,sort values based on ascending => generally ascending data or use => ascending =True
                      descending => use   => ascending =False

In [5]:
name.rank(ascending=True,method='max')   

0    4.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [6]:
frame=pd.DataFrame({'b':[1,2,3,4,5],'a':[1,2,3,4,7],'c':[2,3,4,5,6]})
frame

b  a  c
0  1  1  2
1  2  2  3
2  3  3  4
3  4  4  5
4  5  7  6

In [7]:
frame.rank(axis='columns')

b    a    c
0  1.5  1.5  3.0
1  1.5  1.5  3.0
2  1.5  1.5  3.0
3  1.5  1.5  3.0
4  1.0  3.0  2.0

In [8]:
frame.rank(method='min')

b    a    c
0  1.0  1.0  1.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  5.0  5.0

               The ranking based on row and columns
The rank() method in Pandas with axis='columns'
calculates the ranks along the columns of a DataFrame rather than along the rows.


When you want to calculate the ranks along the rows of a DataFrame,
you would use axis=1 in the rank() method in Pandas.    



check once again 

 which all are works
 
        axis=0           # along row
        axis=1             # along column
        axis='column'      # along column

In [9]:
import pandas as pd

data = {'A': [3, 1, 2],
        'B': [9, 7, 6],
        'C': [1, 10, 11]}
df = pd.DataFrame(data)

                                        # column wise    0 line 1 line 2 line in index

column_ranks = df.rank(axis='columns')             #A  B   C
print( "column wise")                             # 3  9  1
                                                  # 1  7   10
print(column_ranks)                               # 2  6   11



row_ranks = df.rank(axis=0)    # row wise   A line B line C line likewise
print("row wise")
print(row_ranks)

column wise
     A    B    C
0  2.0  3.0  1.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0
row wise
     A    B    C
0  3.0  3.0  1.0
1  1.0  2.0  2.0
2  2.0  1.0  3.0


# Indexing  and Reindexing

 

# i) Indexing   
 index are immutable and thus can't modify by users
 
 

Create index  and returning index
    using range data


In [13]:
import pandas as pd 
data=pd.Series(range(3),index=['2','3','4'])
data.index

Index(['2', '3', '4'], dtype='object')

In [14]:
indexing=data.index
indexing[1:]

Index(['3', '4'], dtype='object')

In [15]:
indexing[1]='d'      # type error,Index does not support mutable operations

TypeError: Index does not support mutable operations

In [18]:
import numpy as np
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [19]:
data2=pd.Series([11,22,33],index=labels)
data2

0    11
1    22
2    33
dtype: int64

In [17]:
# index also behave like a fixed size set



frame


b  a  c
0  1  1  2
1  2  2  3
2  3  3  4
3  4  4  5
4  5  7  6

In [21]:
frame.columns

Index(['b', 'a', 'c'], dtype='object')

In [22]:
'b' in frame.columns

True

In [25]:
'1' in frame.columns

False

In [33]:
# index contain duplicate labels
dup_labels=pd.Index(['a','a','b','c'])
dup_labels

Index(['a', 'a', 'b', 'c'], dtype='object')

In [34]:
dup_labels.is_unique


False

In [36]:
not_dup_labels=pd.Index(['w','a','b','c'])
not_dup_labels

Index(['w', 'a', 'b', 'c'], dtype='object')

In [37]:
not_dup_labels.is_unique

True

In [39]:
not_dup_labels.delete

<bound method Index.delete of Index(['w', 'a', 'b', 'c'], dtype='object')>

In [43]:
not_dup_labels.isin


<bound method Index.isin of Index(['w', 'a', 'b', 'c'], dtype='object')>

   some Index  Methods :
    
    
    
    append                concatenate with additional index object ,producting new index
    difference            compute set difference as an index
    intersection          compute set intersection
    union                 compute set union
    isin                  compute boolean array indicating whether each value is contained in the passed collection
    delete                compute new index with element at index i deleted
    drop                  compute new index by deleting passed values

    insert                compute new index by inserting element at index i
    is_monotonic          Returns true if each element is > or = to previous element
    is_unique             Returns true if index has no duplicates
    unique                compute array of unique values in the index

In [45]:
# try out these methods  

# ii)Reindexing

In [ ]:
reindex method also have arguments



index 
method       => interpolation =>forward 'ffill', backward 'bfill'
fill_value  =>substitute value to use when introducing  missing data by reindexing
limit
tolerance
level    =>   match simple index on level of multiindex otherwise select subset of
copy      =>  If True copy underlying data even if new index is equal to old index 
             if False donot copy  the data when index are equal

In [46]:
data=pd.Series([2,5,5,6,7],index=['a','b','c','d','e'])
data

a    2
b    5
c    5
d    6
e    7
dtype: int64

In [48]:
data2=data.reindex(['a','b','t','s','h'])
data2

a    2.0
b    5.0
t    NaN
s    NaN
h    NaN
dtype: float64

In [51]:
# reindexed values represented as NaN

import pandas as pd

data = {
"age": [50, 40, 30, 40],
"qualified": [True, False, False, False]
}
idx = ["Sally", "Mary", "John", "Monica"]
df = pd.DataFrame(data, index=idx)

newidx = ["Robert", "Cindy", "Chloe", "Pete"]
newdf = df.reindex(newidx)                    #  new index  doesnot equal to old index , that's why it returns NaN
print(newdf)

        age qualified
Robert  NaN       NaN
Cindy   NaN       NaN
Chloe   NaN       NaN
Pete    NaN       NaN


In [56]:
import pandas as pd
data={'age':[49,45],'name':['niva','nivi']}
indx=[2,3]
df=pd.DataFrame(data,index=indx)
new_indx=['a','b']
newidx=df.reindex(new_indx)
newidx

age name
a  NaN  NaN
b  NaN  NaN

In [58]:

df.reindex(range(3),method='ffill')
data

{'age': [49, 45], 'name': ['niva', 'nivi']}

In [65]:
frame=pd.DataFrame(np.arange(9).reshape(3,3)),index=['a','b','c'],columns==['column1','column2','column3']   # error check this 
frame

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (992013362.py, line 1)

In [67]:
states=['tn','hh','dd']
reframe=frame.reindex(columns=states)           # column name only changed
reframe

tn  hh  dd
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN

In [3]:
import pandas as pd
import numpy as np
data={'name':['niva','shar','sanju']
     ,np.nan:['19','18','16']}
df=pd.DataFrame(data)
df.isnull()

name    NaN
0  False  False
1  False  False
2  False  False

In [4]:
df.notnull()

name   NaN
0  True  True
1  True  True
2  True  True

In [11]:
import pandas as pd
import numpy as np
data={'name':['niva',np.nan,'sanju']
     ,np.nan:['19','18',np.nan]}
df=pd.DataFrame(data)
df.fillna(0)

name NaN
0   niva  19
1      0  18
2  sanju   0

In [12]:

df.fillna(method='bfill')

name  NaN
0   niva   19
1  sanju   18
2  sanju  NaN

In [14]:
df.iloc[:1,1]

0    19
Name: nan, dtype: object

In [15]:
df.iloc[2,:2]

name    sanju
NaN       NaN
Name: 2, dtype: object

In [ ]:
SAMPLE PROGRAM

In [1]:
import pandas as pd
import numpy as np
column=['a','b','c','d','e']
index=['A','B','C','D','E']
df=pd.DataFrame(np.random.rand(5,5),columns=column,index=index)
print(df)
re_indexed=df.reindex(['B','D','A','C','E'])
print(re_indexed)

          a         b         c         d         e
A  0.180164  0.706458  0.651602  0.407392  0.239765
B  0.968994  0.853227  0.803450  0.928243  0.150734
C  0.826725  0.233518  0.282751  0.512691  0.162685
D  0.003031  0.385660  0.729674  0.379215  0.910797
E  0.475828  0.049215  0.088729  0.996730  0.969761
          a         b         c         d         e
B  0.968994  0.853227  0.803450  0.928243  0.150734
D  0.003031  0.385660  0.729674  0.379215  0.910797
A  0.180164  0.706458  0.651602  0.407392  0.239765
C  0.826725  0.233518  0.282751  0.512691  0.162685
E  0.475828  0.049215  0.088729  0.996730  0.969761


In [11]:
again_re_index=['U','A','B','O','Y']
new_df=df.reindex(again_re_index)
new_df

a         b         c         d         e
U       NaN       NaN       NaN       NaN       NaN
A  0.338796  0.110059  0.398613  0.510555  0.932533
B  0.928588  0.445105  0.411387  0.059621  0.791675
O       NaN       NaN       NaN       NaN       NaN
Y       NaN       NaN       NaN       NaN       NaN

In [ ]:
# see difference

In [ ]:
REINDEXING is in the column using the axes to reindex.
one can reindex single or multiple columns by using reindex method and by specifying the axis to reindex .
Default values in the new index, that are not present in the database  are assign as NaN

misssing values from the DataFrame can be fill by passing the value to the keyword "fillvalue".This fill value will replace NaN.

In [6]:

re_indexed=df.reindex(again_re_index,axis='columns',fill_value='datamissing')
print(re_indexed)

             U            A            B            O            Y
A  datamissing  datamissing  datamissing  datamissing  datamissing
B  datamissing  datamissing  datamissing  datamissing  datamissing
C  datamissing  datamissing  datamissing  datamissing  datamissing
D  datamissing  datamissing  datamissing  datamissing  datamissing
E  datamissing  datamissing  datamissing  datamissing  datamissing


In [10]:
re_indexed.fillna(0)

U            A            B            O            Y
A  datamissing  datamissing  datamissing  datamissing  datamissing
B  datamissing  datamissing  datamissing  datamissing  datamissing
C  datamissing  datamissing  datamissing  datamissing  datamissing
D  datamissing  datamissing  datamissing  datamissing  datamissing
E  datamissing  datamissing  datamissing  datamissing  datamissing

In [2]:
import pandas as pd
data={'age':[50,70,40,30],'qualified':['true','false','false','true']}
idx=['niva','nivi','aami','loga']
df=pd.DataFrame(data,index=idx)
print("---------BEFORE-------")
print(df)
new_idx=['keerthi','nithish','shar','sanju']
df=pd.DataFrame(new_idx)
print("------Afters--------")
print(df)

---------BEFORE-------
      age qualified
niva   50      true
nivi   70     false
aami   40     false
loga   30      true
------Afters--------
         0
0  keerthi
1  nithish
2     shar
3    sanju


# HIERARCHICAL INDEXING

     

In [ ]:
It is also known as Multi level indexing , is a powerful in pandas,a popular  python data munipulation library.

It allows you to work with higher dimensional data within a DataFrame by creating multiple levels
by creating multiple levels o indexes on rows and columns.

This feature enables you to represent and manipulate complex data structures more efficiently.

It provides a way for you to work with higher dimensional data in a lower dimensional form.


In [3]:
import pandas as pd
import numpy as np
data=pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,3,1,2,d2,3]])
data

a  1   -0.658639
   2    0.959597
   3    1.488763
b  1    0.918826
   3   -0.372733
c  1   -0.888725
   2    1.763236
d  2    1.719244
   3   -1.014291
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
data['b']

1    0.918826
3   -0.372733
dtype: float64

In [6]:
data['b':'c']

b  1    0.918826
   3   -0.372733
c  1   -0.888725
   2    1.763236
dtype: float64

In [7]:
data.loc[['b','d']]

b  1    0.918826
   3   -0.372733
d  2    1.719244
   3   -1.014291
dtype: float64

In [8]:
data.loc[:,2]

a    0.959597
c    1.763236
d    1.719244
dtype: float64

In [9]:
  data.unstack()

1         2         3
a -0.658639  0.959597  1.488763
b  0.918826       NaN -0.372733
c -0.888725  1.763236       NaN
d       NaN  1.719244 -1.014291

In [10]:
data.unstack().stack()

a  1   -0.658639
   2    0.959597
   3    1.488763
b  1    0.918826
   3   -0.372733
c  1   -0.888725
   2    1.763236
d  2    1.719244
   3   -1.014291
dtype: float64

In [20]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],
                   columns=[['ohio','ohio','colorado'],['Green','Red','Red']])
frame

ohio     colorado
    Green Red      Red
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

**What is Hierarchical Indexing?

Hierarchical indexing, also known as multi-indexing,
enables you to have multiple levels of indices for both rows and columns in a pandas DataFrame. 
It provides a way to represent higher-dimensional data in a tabular, two-dimensional structure.



**Example:   Creating a DataFrame with Hierarchical Indexing


In [2]:
import pandas as pd
import numpy as np

                                                            # Creating multi-level index arrays for rows and columns
rows_index = [['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
columns_index = [['Ohio', 'Ohio', 'Colorado'], ['Green', 'Red', 'Red']]

                                                                  # Creating the multi-index DataFrame
data = np.arange(12).reshape((4, 3))
multi_index = pd.DataFrame(data, index=rows_index, columns=columns_index)

                                                                     # Naming the index levels
multi_index.index.names = ['Alphabet', 'Number']
multi_index.columns.names = ['State', 'Color']                        # Note , we can give index's name also

print(multi_index)


State            Ohio     Colorado
Color           Green Red      Red
Alphabet Number                   
A        1          0   1        2
         2          3   4        5
B        1          6   7        8
         2          9  10       11


In [3]:
multi_index

State            Ohio     Colorado
Color           Green Red      Red
Alphabet Number                   
A        1          0   1        2
         2          3   4        5
B        1          6   7        8
         2          9  10       11

# Reordering and Sorting levels  in Hierachical  indexing 

data.swaplevel('level1','level2')
data.sort_index(level=0 or 1 or based on indexlevel)
data.sort_index() => it sort based on 1st level that means  zero is first level like range (0,1,2,3....)

In [5]:
multi_index.swaplevel('Alphabet','Number')     # swaping index level

State            Ohio     Colorado
Color           Green Red      Red
Number Alphabet                   
1      A            0   1        2
2      A            3   4        5
1      B            6   7        8
2      B            9  10       11

In [9]:
multi_index.sort_index(level=1)       # sort the data using only the values in a single level
                                      # Here two level= 0,1 

State            Ohio     Colorado
Color           Green Red      Red
Alphabet Number                   
A        1          0   1        2
B        1          6   7        8
A        2          3   4        5
B        2          9  10       11

In [11]:
multi_index.sort_index(level=0)         

State            Ohio     Colorado
Color           Green Red      Red
Alphabet Number                   
A        1          0   1        2
         2          3   4        5
B        1          6   7        8
         2          9  10       11

In [10]:
multi_index.swaplevel(0,1).sort_index(level=0)    #    lexicographincally sorted by the indicated level

State            Ohio     Colorado
Color           Green Red      Red
Number Alphabet                   
1      A            0   1        2
       B            6   7        8
2      A            3   4        5
       B            9  10       11

**Features

**Accessing Data:

.loc[] allows you to access data based on the index levels.

In [26]:
# Accessing a specific cell
cell_value = multi_index.loc[('A', 1), ('Ohio', 'Green')]
cell_value

0

In [ ]:
Partial Indexing:

Partial indexing allows selecting subsets of the data at various levels.

In [29]:
# Selecting rows with Alphabet 'A'
subset_A = multi_index.loc['A']

# Selecting columns with State 'Ohio'
ohio_data = multi_index.loc[:, 'Ohio']
print("subset A")
print(subset_A)
print("ohio_data")
print(ohio_data)

subset A
State   Ohio     Colorado
Color  Green Red      Red
Number                   
1          0   1        2
2          3   4        5
ohio_data
Color            Green  Red
Alphabet Number            
A        1           0    1
         2           3    4
B        1           6    7
         2           9   10


**Index Slicing:

Slicing lets you select a range of data based on the index levels.

In [33]:
import pandas as pd
import numpy as np

# Create the DataFrame with a MultiIndex
rows_index = [['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
columns_index = [['Ohio', 'Ohio', 'Colorado'], ['Green', 'Red', 'Red']]
data = np.arange(12).reshape((4, 3))
multi_index = pd.DataFrame(data, index=rows_index, columns=columns_index)

# Sort the index levels
multi_index.sort_index(axis=0, level=0, inplace=True)  # Sort rows
multi_index.sort_index(axis=1, level=0, inplace=True)  # Sort columns

# Now, perform slicing operations
slice_rows = multi_index.loc['A':'B']
slice_columns = multi_index.loc[:, ('Ohio', 'Green'):('Colorado', 'Red')]

print("Slice Rows:")
print(slice_rows)
print("\nSlice Columns:")
print(slice_columns)


Slice Rows:
    Colorado  Ohio    
         Red Green Red
A 1        2     0   1
  2        5     3   4
B 1        8     6   7
  2       11     9  10

Slice Columns:
Empty DataFrame
Columns: []
Index: [(A, 1), (A, 2), (B, 1), (B, 2)]


**Stacking and Unstacking:

stack() and unstack() functions convert between hierarchical and regular indexing for rows and columns.


In [37]:
print(multi_index.columns.names)  # Print the names of levels in columns
print(multi_index.columns.levels) # Print the actual levels in columns


[None, None]
[['Colorado', 'Ohio'], ['Green', 'Red']]


In [14]:
stack_index_data=multi_index.stack()
stack_index_data

State                  Colorado  Ohio
Alphabet Number Color                
A        1      Green       NaN     0
                Red         2.0     1
         2      Green       NaN     3
                Red         5.0     4
B        1      Green       NaN     6
                Red         8.0     7
         2      Green       NaN     9
                Red        11.0    10

In [15]:
stack_index_data.unstack()

State           Colorado        Ohio    
Color              Green   Red Green Red
Alphabet Number                         
A        1           NaN   2.0     0   1
         2           NaN   5.0     3   4
B        1           NaN   8.0     6   7
         2           NaN  11.0     9  10

**Conclusion

Data selection performance is much better on hierarchically indexed objects 
if the index is lexicographically sorted starting with the outermost level 
[-that is  the result of calling sort_index(level=0)or sort_index()].


Hierarchical indexing in pandas is a powerful feature allowing the representation and manipulation of complex,
higher-dimensional data within a DataFrame structure. 

It offers flexibility in data selection, manipulation, and analysis through its various functionalities, 
making it a valuable tool in data analysis and manipulation workflows.